# Generated by Django 4.0.6 on 2022-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='school'),
        ),
    ]
