# Generated by Django 4.0.6 on 2022-08-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_userinfo_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(max_length=10),
        ),
    ]
