# Generated by Django 4.0.6 on 2022-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_userinfo_gender_alter_userinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('', 'select'), ('Viewer', 'Viewer'), ('Student', 'Student')], default='Like', max_length=10),
        ),
    ]
