# Generated by Django 4.0.6 on 2022-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_userinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('', 'select'), ('male', 'Male'), ('female', 'Female')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(choices=[('', 'select'), ('Viewer', 'Viewer'), ('Student', 'Student')], max_length=10),
        ),
    ]
