# Generated by Django 4.0.6 on 2022-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_userinfo_gender_alter_userinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(max_length=10),
        ),
    ]
